### ISSUE TITLE
Error in biomaj-cli 'show'

### ISSUE THREAD

**Issue by mboudet** [genouest/biomaj-daemon#6]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/biomaj_daemon/daemon/biomaj_daemon_web.py", line 1086, in biomaj_daemon
    (res, msg) = biomaj_client_action(options_object, config)
  File "/usr/local/lib/python3.9/dist-packages/biomaj_daemon/daemon/utils.py", line 955, in biomaj_client_action
    return biomaj_show(options, config)
  File "/usr/local/lib/python3.9/dist-packages/biomaj_daemon/daemon/utils.py", line 318, in biomaj_show
    return (True, msg)
UnboundLocalError: local variable 'msg' referenced before assignment
```

**Comment by osallou** [comment]
case where no production release found (total or with option *release*)

msg should be initialized to None at function start and before leaving

    if len(results) == 0:
        reutrn (False, "no production release found")

:-)

**Comment by mboudet** [comment]
Thank your Mr @osallou :p

**Comment by osallou** [comment]
C est gratuit, ahhh la nostalgie ;-)

**Comment by abretaud** [comment]
Ouah, un nouveau ministère contributeur :heart_eyes:
